spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/rs-parking-node?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;autoReconnectForPools=true
    username: root
    password: 1234
  jwt:
    issuer: hweetae@gmail.com
    secret_key: security_survey
server:
  port: 8083